sudo: required

services:
  -docker
  
language: python

before_install:
- docker pull laszewski/cloudmesh-tex:0.0.1
- docker run laszewski/cloudmesh-tex:0.0.1 /bin/sh -c "cd /book; git pull"

script:
  - python --version
  - cd /book; git pull
  - cd /book; make travis

